### ISSUE TITLE
关于运行问题

### ISSUE THREAD

**Issue by Lucky-watermelon** [296452965/flask_bulletin_board#2]
博主您好：

  非常感谢您的分享，我在尝试站在您的肩膀上学习时，遇到了一些问题，我在查看了settings.py文件后，觉得网页的登录页面的账号及密码可能都为root，但是遇到了下面的问题

![image](https://user-images.githubusercontent.com/83643234/191742348-c40c6160-faec-4035-8652-24dfbaec9897.png)
这对我真的很难解决，我猜测是还需要一些准备工作，如database的创建，和其中table的创建，及其命名和密码设置，但是我不清楚如何设置。

请原谅我愚蠢的提问，作为小白我现在还很理解您的代码，期待您的回复！

此致
   hzy

**Comment by 296452965** [comment]
> 博主您好：
> 
> 非常感谢您的分享，我在尝试站在您的肩膀上学习时，遇到了一些问题，我在查看了settings.py文件后，觉得网页的登录页面的账号及密码可能都为root，但是遇到了下面的问题
> 
> ![image](https://user-images.githubusercontent.com/83643234/191742348-c40c6160-faec-4035-8652-24dfbaec9897.png) 这对我真的很难解决，我猜测是还需要一些准备工作，如database的创建，和其中table的创建，及其命名和密码设置，但是我不清楚如何设置。
> 
> 请原谅我愚蠢的提问，作为小白我现在还很理解您的代码，期待您的回复！
> 
> 此致 hzy

报错的问题在于没连上数据库，所以你的数据库配置可能和我文件中的不一致。
这是我第一次上传项目，没有充分考虑项目移植到其他环境下的运行问题。
详细交流，可以联系我的微信 cyk-21

**Comment by Lucky-watermelon** [comment]
已完成
